spring.application.name=compilador
server.port=8080
compilador.solc.ruta=C:\\Users\\cristian.gomez\\Documents\\compilador\\solc\\compilador-solc.exe
compilador.solc.timeout-segundos=20
spring.mongodb.uri=mongodb://127.0.0.1:27017/smacly
spring.data.mongodb.auto-index-creation=true
compilador.vyper.ruta=C:\\Users\\cristian.gomez\\Documents\\compilador\\vyper\\vyper0-4-3compilador.exe
compilador.vyper.timeout-segundos=20
# Tamaño máximo permitido para el archivo Excel
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB